# Generated by Django 4.2.20 on 2025-04-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlistID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('spotifyID', models.CharField(max_length=200)),
                ('generatedBy', models.IntegerField(blank=True, null=True)),
                ('songList', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songID', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('spotifyURI', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
